### ISSUE TITLE
Feature request: HTML example generation

### ISSUE THREAD

**Issue by martijn94** [freshheads/svg-spritemap-webpack-plugin#20]
Hey,

Would be awesome to have a HTML example page generator like https://github.com/jkphl/svg-sprite. So you can preview and snippet the icons quickly.

Thanks!

**Comment by cascornelissen** [comment]
Since this is just a Webpack plugin I don't feel like adding an example page generator would be a good idea. 

Performance is key in these kinds of projects and adding onto the process takes speed away. We could always hide it behind a flag/option but this addition would still make the codebase unnecessarily more complex.

You can always open the generated SVG in your browser and use your browser's inspector if you need to match the names to a sprite.

**Comment by martijn94** [comment]
Makes sense, will look into the second option!

Thanks.
